### ISSUE TITLE
Module Url is probably malformed in utils/get_activity/module.php? 

### ISSUE THREAD

**Issue by deedey** [davidpesce/moodle-logstore_xapi#186]
**Description**
- In "**src/transformer/utils/get_activity**" on line 34 of **module.php** we have:
            _**'id' => $config['app_url'].'/mod/'.$moduletype.'/view.php?id='.$module->id,**_
 $module_id malforms the url because it links the ID in the module ad-hoc but we want to link to the  context instancied .
The real url of module is based on the field " **contextinstanceid** "
And the "_event_module function_" in **event_module.php** can send this field content like this:
          _**$contextid = $event->contextinstanceid;
    return utils\get_activity\module($config, $moduletype, $module, $contextid, $lang);**_
Updating this make **module.php** like this : 
_**function module(array $config, $moduletype, $module, $contextid, $lang) {
    return [
        'id' => $config['app_url'].'/mod/'.$moduletype.'/view.php?id='.$contextid,**_
With these changes, it work fine...

**Version**
- Moodle -> 3.5
- Logstore_xapi -> Last

**Steps to reproduce the bug**
1. Verify sent JSON statement

**Client information**
- OS: All
- Browser: Chrome, Filezilla, Safari all newer vesrsions

**Additional information**
- Using Annulab LRS

**Comment by ryasmi** [comment]
Hey @deedey, I don't think it'll be malformed, do you have an example where it is malformed so I can better understand your issue?

**Comment by deedey** [comment]
Hi @ryansmith94 ,
I'll try to give you some explanations about what I said:
First, in logstore_standard_log table we find this organisation: 
![logs](https://user-images.githubusercontent.com/5656024/42865199-301a7ee0-8a69-11e8-99be-fb5a69f9ea3e.jpg)
ObjectID is the ID of the object wiki (6) in wiki table with a correlation to the course ID (291) named 'xAPI et le Learning Record Storage'.
![wiki](https://user-images.githubusercontent.com/5656024/42865482-0b455d46-8a6a-11e8-9f54-7608d6ebaac7.jpg)

The URL which launchs this wiki is 
http://heliantice.agrosupdijon.fr/mod/wiki/view.php?id=2776
which gives this:
![url](https://user-images.githubusercontent.com/5656024/42865438-edb5ad1c-8a69-11e8-84cc-1b422e36e425.jpg)
If we reconstruct the url with the module_ID by doing this in **event_module.php**:
    _$moduleid = $event->objectid;
    $module = $repo->read_record_by_id($moduletype, $moduleid);_
    $moduleid = 6;
    $module = $repo->read_record_by_id('wiki', 6);
We obtain in **module.php** this:
        _'id' => $config['app_url'].'/mod/'.$moduletype.'/view.php?id='.$module->id,_ like this:
        'id' =>http://heliantice.agrosupdijon.fr /mod/wiki/view.php?id=6,
which is far from
        'id' =>http://heliantice.agrosupdijon.fr/mod/wiki/view.php?id=2776

In my LRS, the URL result is:
   _"object":{
      "id":"http://heliantice.agrosupdijon.fr/mod/wiki/view.php?id=6",
      "definition":{
         "type":"http://id.tincanapi.com/activitytype/lms/module",
         "name":{
            "en":"xAPI et le Learning Record Storage"
         }
      }
   },_
![wikierror](https://user-images.githubusercontent.com/5656024/42867307-8b4814c0-8a6f-11e8-8a00-0e8c63790767.jpg)

with the mistake
but with the correction I have this;
 _"object":{
      "id":"http://heliantice.agrosupdijon.fr/mod/wiki/view.php?id=2776",
      "definition":{
         "type":"http://id.tincanapi.com/activitytype/lms/module",
         "name":{
            "en":"xAPI et le Learning Record Storage"
         }
      }
   },_
 Regards
Dey

**Comment by ryasmi** [comment]
Hey @deedey, great explanation! Thank you very much, I'll see if I can change this to use the course module ID (via the `contextinstanceid`) 👍

**Comment by ryasmi** [comment]
This issue seems to be a little trickier once you get into it, so I'm going to help Lee with an example recipe for question submissions first so I'm not blocking Lee from making progress.

**Comment by deedey** [comment]
Hi @ryansmith94 ,
I don't undestand what you mean by your last review.
If you agree I give you the code I use after updating the two scripts concerned by this mistake.
Or if you agree, I can do a pull request about that
Regards

**Comment by ryasmi** [comment]
It doesn't look like the code you sent over will fix the issue in every case only most cases. You're welcome to make a PR though.

**Comment by ryasmi** [comment]
Fixing existing custom events (not course_module_viewed)

- [X] mod_assign #206
- [X] mod_facetoface #221
- [X] mod_feedback #207 
- [x] mod_forum (Unnecessary)
- [X] mod_quiz #205
- [X] mod_scorm #210

Fixing course_module_viewed events

- [X] `\mod_book\event\course_module_viewed` #221
- [X] `\mod_chat\event\course_module_viewed` #221
- [X] `\mod_choice\event\course_module_viewed` #221
- [X] `\mod_data\event\course_module_viewed` #221
- [X] `\mod_facetoface\event\course_module_viewed` #221
- [X] `\mod_feedback\event\course_module_viewed` #207
- [X] `\mod_folder\event\course_module_viewed` #221
- [X] `\mod_forum\event\course_module_viewed` #221
- [X] `\mod_glossary\event\course_module_viewed` #221
- [X] `\mod_imscp\event\course_module_viewed` #221
- [X] `\mod_lesson\event\course_module_viewed` #221
- [X] `\mod_lti\event\course_module_viewed` #221
- [X] `\mod_page\event\course_module_viewed` #221
- [X] `\mod_quiz\event\course_module_viewed` #221
- [X] `\mod_quiz\event\attempt_viewed` #221
- [X] `\mod_resource\event\course_module_viewed` #221
- [X] `\mod_scorm\event\course_module_viewed` #221
- [X] `\mod_survey\event\course_module_viewed` #221
- [X] `\mod_url\event\course_module_viewed` #221
- [X] `\mod_wiki\event\course_module_viewed` #221
- [X] `\mod_workshop\event\course_module_viewed` #221

For the `course_module_viewed` events, my plan is to actually create a transformer for each rather than using the `all/course_module_viewed` transformer. This will allow every module to have it's own unique activity type that better matches [the xAPI vocab registry](http://xapi.vocab.pub/activity-types/index.html). This will also allow us to remove `module` and `event_module` from the `utils/get_activity` directory. Obviously this will duplicate a lot of code but we can refactor where possible afterwards.

**Comment by deedey** [comment]
Thanks a lot @ryansmith94 
Great work
Dey

**Comment by ryasmi** [comment]
You're welcome @deedey. Thank you, sorry it took a bit longer than a normal fix 👍
